[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -jar app.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/actuator/health"
healthcheckTimeout = 100

[build.watchPatterns]
patterns = ["src/**", "pom.xml", "Dockerfile"]

